apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fraud-mlops-pvc
  namespace: fraud-mlops
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: fraud-mlops-pv
