apiVersion: v1
kind: ResourceQuota
metadata:
  name: fraud-mlops-quota
  namespace: fraud-mlops
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "12"
    limits.memory: 24Gi
    persistentvolumeclaims: "5"
